### ISSUE TITLE
Screenshots ignore background color

### ISSUE THREAD

**Issue by louh** [tangrams/tangram#375]
Screenshot of TRON 2.0, as seen on screen (with additional data by Patricio):

![image](https://cloud.githubusercontent.com/assets/2553268/17382136/61985b26-599d-11e6-9f93-1b307b882382.png)

Similar screenshot saved directly from [Tangram Play, same scene file](https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F0a0ccfcf642062d5139a157fc4e6e517%2Fraw%2F11b4c41cc2a69afb202d0b51768a7bddbb2778bc%2Fscene.yaml#2.8281/31.71/-16.83):

![tangram- 2 8281 31 7112 -16 8329_2016-08-03_17 12 55](https://cloud.githubusercontent.com/assets/2553268/17382175/8e49aef4-599d-11e6-9f04-ab9304daa2f3.png)

The alphas are preserved.

I think this is actually not what someone might be expecting because what they get isn't what they see (even if it's sometimes helpful for alphas to be preserved). Since the background color and the screenshot functionality is all done in Tangram I thought I'd file it for discussion here first.

**Comment by bcamper** [comment]
@meetar when you are back can you take a look at what's happening here

**Comment by meetar** [comment]
No longer seeing this, @lou can you confirm that this is resolved?

**Comment by blair1618** [comment]
I suspect that this no longer happens for this particular example because the 'tron' scene was recently updated to not use opacity for the stripe effect (https://github.com/tangrams/tron/commit/0fdea20ccb19bd59177a93c5dbc8a1371acfb822). Anything that still outputs alpha values < 1 will probably still have this issue.

**Comment by meetar** [comment]
Good catch, I'll make a new test case.

**Comment by meetar** [comment]
Confirmed: transparent pixels remain transparent after a screenshot, and background colors will show through. In the case of Play it's `#222`, which is the `background-color` of the `.leaflet-container` div, in the Mac Preview app it's `#dedede`, and in a blank web page it's `#fff`. Hypothetically the screenshot mechanism could check for a `scene.config.scene.background.color` property and composite this color behind the screenshot – @louh, is that the behavior you'd expect?

**Comment by louh** [comment]
Is the background color property something one would set inside a Tangram scene file, then? Or would you try to do something like `getComputedStyle(document.getElementById('map')).backgroundColor`?

I tried `getComputedStyle(scene.container).backgroundColor` and it did not give me the correct results, which is unfortunate.

**Comment by louh** [comment]
Other than that - I would expect the screenshot saved is what the user observes on their screen, so if compositing a background color is the best way to do this, then 👍

**Comment by meetar** [comment]
I'd probably check for both, cf https://mapzen.com/documentation/tangram/scene/#background

**Comment by meetar** [comment]
Revisiting this – the `background: {color: }` parameter is now respected by a screenshot, and if none is set, the background of the map is transparent. We have no control over what goes behind the map (and it's not accessible to the canvas anyway) so this seems like acceptable behavior. Agreed?

**Comment by louh** [comment]
That sounds fair to me!
